from moelab.moedl.grouped_glu import GroupedGLU
from moelab.moedl.modeling_moedl import MoedlMLP

from dataclasses import dataclass
import torch

@dataclass
class Cfg_GroupedGLU:
    n_group: int = 1
    d: int = 768
    dff: int = 2048

@dataclass
class Cfg_MoedlMLP:
    hidden_size: int = 768
    intermediate_size: int = 2048
    mlp_bias: bool = False
    hidden_act: str = "silu"

# Note that the following is generated by sonnet 4.6.

PASS = "\033[32mPASS\033[0m"
WARN = "\033[33mWARN\033[0m"
FAIL = "\033[31mFAIL\033[0m"

def _sync_weights(gg: GroupedGLU, mlp: MoedlMLP):
    """Copy GroupedGLU (n_group=1) weights into a MoedlMLP so they are identical."""
    with torch.no_grad():
        mlp.gate.weight.copy_(gg.weight_gate.squeeze(0))
        mlp.up.weight.copy_(gg.weight_up.squeeze(0))
        mlp.down.weight.copy_(gg.weight_down.squeeze(0))


def _check(label: str, a: torch.Tensor, b: torch.Tensor, atol: float, rtol: float):
    ok = torch.allclose(a.float(), b.float(), atol=atol, rtol=rtol)
    max_err = (a.float() - b.float()).abs().max().item()
    if not ok:
        status = FAIL
    elif max_err > 0:
        status = WARN
    else:
        status = PASS
    print(f"  {status}  {label:<30s}  max_err={max_err:.3e}")
    return ok


def run_comparison(dtype_label: str, model_dtype: torch.dtype, use_autocast: bool):
    print(f"\n{'='*60}")
    print(f"  dtype={dtype_label}  autocast={use_autocast}")
    print(f"{'='*60}")

    device = "cuda"
    atol = 1e-4 if model_dtype == torch.float32 else 5e-2

    cfg_gg  = Cfg_GroupedGLU()
    cfg_mlp = Cfg_MoedlMLP()

    # Build both models in fp32, sync weights, then cast.
    gg  = GroupedGLU(cfg_gg.n_group, cfg_gg.d, cfg_gg.dff, device=device)
    mlp = MoedlMLP(cfg_mlp).to(device)
    _sync_weights(gg, mlp)

    gg  = gg.to(model_dtype)
    mlp = mlp.to(model_dtype)

    n_tokens = 31  # arbitrary
    x_base = torch.randn(n_tokens, cfg_gg.d, device=device, dtype=model_dtype)
    offs   = torch.tensor([n_tokens], dtype=torch.int32, device=device)

    x_gg  = x_base.clone().requires_grad_(True)
    x_mlp = x_base.clone().requires_grad_(True)

    ctx = torch.autocast(device_type="cuda", dtype=model_dtype) if use_autocast else torch.no_grad().__class__()  # dummy ctx

    # ---- forward ----
    if use_autocast:
        with torch.autocast(device_type="cuda", dtype=model_dtype):
            out_gg  = gg(x_gg, offs)
            out_mlp = mlp(x_mlp)
    else:
        out_gg  = gg(x_gg, offs)
        out_mlp = mlp(x_mlp)

    all_pass = True
    all_pass &= _check("forward output", out_gg, out_mlp, atol=atol, rtol=atol)

    # ---- backward ----
    out_gg.sum().backward()
    out_mlp.sum().backward()

    all_pass &= _check("grad  x (input)",        x_gg.grad,             x_mlp.grad,             atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_gate / gate", gg.weight_gate.grad.squeeze(0), mlp.gate.weight.grad, atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_up   / up",   gg.weight_up.grad.squeeze(0),   mlp.up.weight.grad,   atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_down / down",  gg.weight_down.grad.squeeze(0), mlp.down.weight.grad, atol=atol, rtol=atol)

    return all_pass


def run_comparison_compiled(dtype_label: str, model_dtype: torch.dtype, backend: str = None):
    """Same as run_comparison but both models are wrapped with torch.compile."""
    backend_label = backend if backend is not None else "inductor"
    print(f"\n{'='*60}")
    print(f"  dtype={dtype_label}  torch.compile({backend_label})  autocast=True")
    print(f"{'='*60}")

    device = "cuda"
    atol = 5e-2

    cfg_gg  = Cfg_GroupedGLU()
    cfg_mlp = Cfg_MoedlMLP()

    # Build both models in fp32, sync weights, then cast.
    gg  = GroupedGLU(cfg_gg.n_group, cfg_gg.d, cfg_gg.dff, device=device)
    mlp = MoedlMLP(cfg_mlp).to(device)
    _sync_weights(gg, mlp)

    gg  = gg.to(model_dtype)
    mlp = mlp.to(model_dtype)

    compile_kwargs = {"backend": backend} if backend is not None else {}
    gg_c  = torch.compile(gg,  **compile_kwargs)
    mlp_c = torch.compile(mlp, **compile_kwargs)

    n_tokens = 31
    x_base = torch.randn(n_tokens, cfg_gg.d, device=device, dtype=model_dtype)
    offs   = torch.tensor([n_tokens], dtype=torch.int32, device=device)

    x_gg  = x_base.clone().requires_grad_(True)
    x_mlp = x_base.clone().requires_grad_(True)

    # ---- forward ----
    with torch.autocast(device_type="cuda", dtype=model_dtype):
        out_gg  = gg_c(x_gg, offs)
        out_mlp = mlp_c(x_mlp)

    all_pass = True
    all_pass &= _check("forward output", out_gg, out_mlp, atol=atol, rtol=atol)

    # ---- backward ----
    out_gg.sum().backward()
    out_mlp.sum().backward()

    all_pass &= _check("grad  x (input)",          x_gg.grad,                      x_mlp.grad,           atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_gate / gate",  gg.weight_gate.grad.squeeze(0), mlp.gate.weight.grad, atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_up   / up",    gg.weight_up.grad.squeeze(0),   mlp.up.weight.grad,   atol=atol, rtol=atol)
    all_pass &= _check("grad  weight_down / down",  gg.weight_down.grad.squeeze(0), mlp.down.weight.grad, atol=atol, rtol=atol)

    return all_pass


if __name__ == "__main__":
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for this comparison.")

    results = {}
    results["fp32"]                  = run_comparison("fp32",  torch.float32,  use_autocast=False)
    results["bf16"]                  = run_comparison("bf16",  torch.bfloat16, use_autocast=True)
    results["bf16_compile"]          = run_comparison_compiled("bf16", torch.bfloat16)
    results["bf16_compile_aot_eager"] = run_comparison_compiled("bf16", torch.bfloat16, backend="aot_eager")



